### PR TITLE
remove sqlite dep

### PR DESCRIPTION
**Pull request by JAertgeerts**
#8

### CODE REVIEW

**Comment by grbspltt** [comment]
can someone please merge this PR??

**Comment by Tyratox** [comment]
May it be possible to push the update to npm?

**Comment by maddy2get** [comment]
Yes, I’ll do that very soon.

**Comment by maddy2get** [comment]
@Tyratox Updated in NPM.

**Comment by Tyratox** [comment]
Cool, thank you!

**Pull request merged**
