### PR TITLE
Update for Sequelize 3.0 fixes #2

### LINKED ISSUE #2: Doesn't work with sequelize 3
Can you fix it?

### PR DESCRIPTION
**Pull request by crisward**
Swapped out success and error for .them and .catch as sequelize for a while has used standard promises.

### CODE REVIEW

**Comment by crisward** [comment]
BTW I've tested this against my project using sequelize 3.0 and it works fine.

**Comment by crisward** [comment]
any chance of an npm version patch, npm publish? (Thanks BTW!)

**Comment by maddy2get** [comment]
Hey @crisward,

I have bumped npm version now. Check it out. 

Let me know if any issues.

**Comment by crisward** [comment]
All working, thanks again.

**Pull request merged**
